// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run FlutterFire CLI to reconfigure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3yr9rfxZ2WH3BR54cGk45kGRTMC6VXw',
    appId: '1:317981426470:android:81a0fb88c4efdc336ff7e7',
    messagingSenderId: '317981426470',
    projectId: 'universityeventnotifier',
    storageBucket: 'universityeventnotifier.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOqWswvf70fTzvBW4a_WXlQcy9diSwnE',
    appId: '1:317981426470:web:e640696f33f77e106ff7e7',
    messagingSenderId: '317981426470',
    projectId: 'universityeventnotifier',
    authDomain: 'universityeventnotifier.firebaseapp.com',
    storageBucket: 'universityeventnotifier.firebasestorage.app',
    measurementId: 'G-2V4DGR2MD0',
  );
}
